import { NextResponse } from "next/server";

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { name, email, password } = body;

    // This is a placeholder for your actual registration logic
    // In a real application, you would save the user to your database

    // Simple validation
    if (!name || !email || !password) {
      return NextResponse.json(
        { message: "Name, email, and password are required" },
        { status: 400 }
      );
    }

    // Mock registration - in a real app, you would save the user to your database
    return NextResponse.json({
      user: {
        id: "3", // In a real app, this would be generated by your database
        name,
        email,
        role: "customer", // Default role for new users
      },
    });
  } catch (error) {
    console.error("Registration error:", error);
    return NextResponse.json(
      { message: "An error occurred during registration" },
      { status: 500 }
    );
  }
}
